name: rebuttal_branavan_craft
recipes: "resources/light/recipes.yaml"
world: 
  name: LightWorld
model: 
  name: ModularACModel
  use_args: true
  featurize_plan: false
  max_subtask_timesteps: 15
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/light/hints.args.yaml"
  max_timesteps: 100
