name: craft_modular_no-curriculum-lmax
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: false
  max_subtask_timesteps: 15
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
