name: craft_modular_task-baseline_unordered
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: false
  featurize_plan: false
  max_subtask_timesteps: 15
  baseline: task
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
